#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Sat Jul 27 19:13:48 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from imagepanel import ImagePanel
from simulator import Sim, Input
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.sim_image = ImagePanel(self, wx.ID_ANY)
        self.sim = Sim()
        self.single_click = wx.Button(self, wx.ID_ANY, "Single")
        self.double_click = wx.Button(self, wx.ID_ANY, "Double")
        self.single_click_copy_1 = wx.Button(self, wx.ID_ANY, "Long")
        self.down_flip = wx.Button(self, wx.ID_ANY, "Down")
        self.up_flip = wx.Button(self, wx.ID_ANY, "Up")
        self.left_flip = wx.Button(self, wx.ID_ANY, "Left")
        self.right_flip = wx.Button(self, wx.ID_ANY, "Right")
        self.azimuth = wx.Slider(self, wx.ID_ANY, 0, 0, 359, style=wx.SL_HORIZONTAL | wx.SL_LABELS)
        self.inclination = wx.Slider(self, wx.ID_ANY, 0, -90, 90, style=wx.SL_HORIZONTAL | wx.SL_LABELS)
        self.roll = wx.Slider(self, wx.ID_ANY, 0, -180, 180, style=wx.SL_HORIZONTAL | wx.SL_LABELS)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, lambda evt: self.sim.set_input(Input.SINGLE_CLICK), self.single_click)
        self.Bind(wx.EVT_BUTTON, lambda evt: self.sim.set_input(Input.DOUBLE_CLICK), self.double_click)
        self.Bind(wx.EVT_BUTTON, lambda evt: self.sim.set_input(Input.LONG_CLICK), self.single_click_copy_1)
        self.Bind(wx.EVT_BUTTON, lambda evt: self.sim.set_input(Input.FLIP_DOWN), self.down_flip)
        self.Bind(wx.EVT_BUTTON, lambda evt: self.sim.set_input(Input.FLIP_UP), self.up_flip)
        self.Bind(wx.EVT_BUTTON, lambda evt: self.sim.set_input(Input.FLIP_LEFT), self.left_flip)
        self.Bind(wx.EVT_BUTTON, lambda evt: self.sim.set_input(Input.FLIP_RIGHT), self.right_flip)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.orientation_changed, self.azimuth)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.orientation_changed, self.inclination)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.orientation_changed, self.roll)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Orientation"), wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 0, 4)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Flip"), wx.VERTICAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Button"), wx.VERTICAL)
        sizer_2.Add(self.sim_image, 1, wx.EXPAND, 0)
        sizer_4.Add(self.single_click, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_4.Add(self.double_click, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_4.Add(self.single_click_copy_1, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_3.Add(sizer_4, 0, wx.ALL | wx.EXPAND, 2)
        sizer_5.Add(self.down_flip, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_5.Add(self.up_flip, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_5.Add(self.left_flip, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_5.Add(self.right_flip, 0, wx.ALIGN_CENTER | wx.ALL, 2)
        sizer_3.Add(sizer_5, 0, wx.ALL | wx.EXPAND, 2)
        label_1 = wx.StaticText(self, wx.ID_ANY, "Azimuth:", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.azimuth, 0, wx.ALL | wx.EXPAND, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "Inclination:", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.inclination, 0, wx.ALL | wx.EXPAND, 0)
        label_3 = wx.StaticText(self, wx.ID_ANY, "Roll:", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.roll, 0, wx.ALL | wx.EXPAND, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_6.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 3)
        sizer_3.Add(sizer_6, 4, wx.ALL, 2)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade
        
    def orientation_changed(self, event):  # wxGlade: MyFrame.<event_handler>
        self.sim.sensor.set_orientation(self.azimuth.GetValue(), self.inclination.GetValue(), self.roll.GetValue())
        
    def message_handler(self, message):
        result = self.sim.handleMessage(message)
        if message[0:2] == [0x01, 0x78]:
            self.sim_image.paintNow(self.sim.get_image())
        return result
        
# end of class MyFrame

class Gui(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class Gui

if __name__ == "__main__":
    gui = Gui(0)
    gui.MainLoop()
