#ifndef UNITY_CONFIG_H
#define UNITY_CONFIG_H
#include <stdfix.h>
#define UNITY_INCLUDE_DOUBLE
#define UNITY_FIXED_PRECISION 0.01
#define UNITY_DOUBLE_PRECISION 0.01
#define UNITY_INCLUDE_FIXED
#define UNITY_FIXED_TYPE accum
#endif
