#ifndef _CEXCEPTION_CONFIG_H
#define _CEXCEPTION_CONFIG_H
enum EXCEPTION_CODES {
    ERROR_UNSPECIFIED=0,
    ERROR_MENU_FULL,
    ERROR_MENU_EMPTY,
    ERROR_STRING_TOO_BIG,
    ERROR_FLASH_STORE_FAILED,
    ERROR_SURVEY_NOT_FOUND,
    ERROR_LASER_READ_FAILED,
    ERROR_NO_SURVEY_DATA,
    ERROR_SURVEY_TOO_BIG,
    ERROR_SURVEY_IS_DISJOINT
};


#define CEXCEPTION_T enum EXCEPTION_CODES
#endif
